# Generated by Django 2.0.3 on 2018-04-04 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Ritika', max_length=100)),
                ('last_name', models.CharField(default='Mittal', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phonenum', models.CharField(max_length=10, unique=True)),
                ('mobile_flag', models.BooleanField(default=False)),
                ('email_flag', models.BooleanField(default=False)),
                ('status_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Department'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
