# Generated by Django 2.0.3 on 2018-04-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthViewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Department')),
            ],
        ),
        migrations.CreateModel(
            name='PortalQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(verbose_name='Date Question is Published')),
                ('deadline', models.DateTimeField(verbose_name='Date to be Answered Within')),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_answered', models.BooleanField(default=False)),
                ('asked_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Account')),
            ],
        ),
        migrations.CreateModel(
            name='PortalRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_answer', models.CharField(max_length=500)),
                ('by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Account')),
                ('ques_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.PortalQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='authviewer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.PortalQuestion'),
        ),
    ]
